/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day06multitempconv;

import javax.swing.JOptionPane;

/**
 *
 * @author Teacher
 */
public class Day06MultiTempConv extends javax.swing.JFrame {

    /**
     * Creates new form Day06MultiTempConv
     */
    public Day06MultiTempConv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupInputs = new javax.swing.ButtonGroup();
        buttonGroupOutputs = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbInCel = new javax.swing.JRadioButton();
        rbInFah = new javax.swing.JRadioButton();
        rbInKel = new javax.swing.JRadioButton();
        rbOutKel = new javax.swing.JRadioButton();
        rbOutFah = new javax.swing.JRadioButton();
        rbOutCel = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        tfOutput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Input");

        tfInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfInputKeyReleased(evt);
            }
        });

        jLabel2.setText("Input Scale");

        jLabel3.setText("Output Scale");

        buttonGroupInputs.add(rbInCel);
        rbInCel.setSelected(true);
        rbInCel.setText("Celsius");
        rbInCel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAnyClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rbAnyMouseReleased(evt);
            }
        });

        buttonGroupInputs.add(rbInFah);
        rbInFah.setText("Fahrenheit");
        rbInFah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAnyClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rbAnyMouseReleased(evt);
            }
        });

        buttonGroupInputs.add(rbInKel);
        rbInKel.setText("Kelvin");
        rbInKel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAnyClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rbAnyMouseReleased(evt);
            }
        });

        buttonGroupOutputs.add(rbOutKel);
        rbOutKel.setText("Kelvin");
        rbOutKel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAnyClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rbAnyMouseReleased(evt);
            }
        });

        buttonGroupOutputs.add(rbOutFah);
        rbOutFah.setText("Fahrenheit");
        rbOutFah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAnyClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rbAnyMouseReleased(evt);
            }
        });

        buttonGroupOutputs.add(rbOutCel);
        rbOutCel.setSelected(true);
        rbOutCel.setText("Celsius");
        rbOutCel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbAnyClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rbAnyMouseReleased(evt);
            }
        });

        jLabel4.setText("Output");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(rbInCel)
                    .addComponent(rbInFah)
                    .addComponent(rbInKel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbOutCel)
                    .addComponent(rbOutFah)
                    .addComponent(rbOutKel)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfInput, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbInCel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbInFah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbInKel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbOutCel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbOutFah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbOutKel)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfInputKeyReleased
        recalulate();
    }//GEN-LAST:event_tfInputKeyReleased

    private void rbAnyClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAnyClicked
        // NOTE: sometimes the event does not happen even if we click
        // that's why we use Mouse Released event instead
        // recalulate();
    }//GEN-LAST:event_rbAnyClicked

    private void rbAnyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbAnyMouseReleased
        recalulate();
    }//GEN-LAST:event_rbAnyMouseReleased

    private void recalulate() {
        // 1. parse the input
        double inVal;
        try {
            inVal = Double.parseDouble(tfInput.getText());
        } catch (NumberFormatException ex) {
            tfOutput.setText("invalid input");
            return;
        }
        // 2. convert to celsius
        double cel;
        if (rbInCel.isSelected()) {
            cel = inVal;
        } else if (rbInFah.isSelected()) {
            cel = (inVal - 32) * 5 / 9;
        } else if (rbInKel.isSelected()) {
            cel = inVal - 273.15;
        } else { // should never happen
            JOptionPane.showMessageDialog(this,
                    "No input radio button selected found",
                    "Internal error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        // 3. convert to the output unit
        double outVal;
        String unit;
        if (rbOutCel.isSelected()) {
            outVal = cel;
            unit = "C";
        } else if (rbOutFah.isSelected()) {
            outVal = cel * 9/5 + 32;
            unit = "F";
        } else if (rbOutKel.isSelected()) {
            outVal = cel + 273.15;
            unit = "K";
        } else { // should never happen
            JOptionPane.showMessageDialog(this,
                    "No output radio button selected found",
                    "Internal error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        // 4. display the result
        String outStr = String.format("%.2f %s", outVal, unit);
        tfOutput.setText(outStr);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day06MultiTempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day06MultiTempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day06MultiTempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day06MultiTempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day06MultiTempConv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupInputs;
    private javax.swing.ButtonGroup buttonGroupOutputs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbInCel;
    private javax.swing.JRadioButton rbInFah;
    private javax.swing.JRadioButton rbInKel;
    private javax.swing.JRadioButton rbOutCel;
    private javax.swing.JRadioButton rbOutFah;
    private javax.swing.JRadioButton rbOutKel;
    private javax.swing.JTextField tfInput;
    private javax.swing.JTextField tfOutput;
    // End of variables declaration//GEN-END:variables
}
