/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day06manyinputs;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Teacher
 */
public class Day06ManyInputs extends javax.swing.JFrame {

    /**
     * Creates new form Day06ManyInputs
     */
    public Day06ManyInputs() {
        initComponents();
        sliderTempStateChanged(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAge = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbAgeBelow18 = new javax.swing.JRadioButton();
        rbAge18to35 = new javax.swing.JRadioButton();
        rbAge36andUp = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        cbPetCat = new javax.swing.JCheckBox();
        cbPetDog = new javax.swing.JCheckBox();
        cbPetOther = new javax.swing.JCheckBox();
        comboContinent = new javax.swing.JComboBox<>();
        lblTemp = new javax.swing.JLabel();
        sliderTemp = new javax.swing.JSlider();
        btRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Name:");

        jLabel4.setText("Continent of residence:");

        jLabel5.setText("Preferred temp.");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Age selection"));
        jPanel1.setName(""); // NOI18N

        buttonGroupAge.add(rbAgeBelow18);
        rbAgeBelow18.setText("Below 18");

        buttonGroupAge.add(rbAge18to35);
        rbAge18to35.setSelected(true);
        rbAge18to35.setText("18-35");

        buttonGroupAge.add(rbAge36andUp);
        rbAge36andUp.setText("36 and up");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbAgeBelow18)
                .addGap(18, 18, 18)
                .addComponent(rbAge18to35)
                .addGap(43, 43, 43)
                .addComponent(rbAge36andUp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAgeBelow18)
                    .addComponent(rbAge18to35)
                    .addComponent(rbAge36andUp))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pets selection"));

        cbPetCat.setText("Cat");

        cbPetDog.setText("Dog");

        cbPetOther.setText("Other");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbPetCat)
                .addGap(47, 47, 47)
                .addComponent(cbPetDog)
                .addGap(51, 51, 51)
                .addComponent(cbPetOther)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPetCat)
                    .addComponent(cbPetDog)
                    .addComponent(cbPetOther))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        comboContinent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asia", "Africa", "Europe", "North America", "South America", "Australia/Oceania", "Antarctica" }));

        lblTemp.setText("xx C");

        sliderTemp.setMajorTickSpacing(5);
        sliderTemp.setMaximum(35);
        sliderTemp.setMinimum(15);
        sliderTemp.setMinorTickSpacing(1);
        sliderTemp.setPaintLabels(true);
        sliderTemp.setPaintTicks(true);
        sliderTemp.setSnapToTicks(true);
        sliderTemp.setValue(22);
        sliderTemp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderTempStateChanged(evt);
            }
        });

        btRegister.setText("Register me");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTemp)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btRegister)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboContinent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sliderTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(lblTemp))
                    .addComponent(sliderTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btRegister)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sliderTempStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderTempStateChanged
        int temp = sliderTemp.getValue();
        lblTemp.setText(String.format("%d C", temp));
    }//GEN-LAST:event_sliderTempStateChanged

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
        String name = tfName.getText();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Name must not be empty",
                    "Input error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        // alternative, requries setting "Action command" for each button in its properties
        // String age = buttonGroupAge.getSelection().getActionCommand();
        String age;
        if (rbAgeBelow18.isSelected()) {
            age = "below18";
        } else if (rbAge18to35.isSelected()) {
            age = "18to35";
        } else if (rbAge36andUp.isSelected()) {
            age = "16andup";
        } else { // Should never happen
            JOptionPane.showMessageDialog(this,
                    "Invalid control flow 100034",
                    "Internal error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        // pets
        ArrayList<String> petsList = new ArrayList<>();
        if  (cbPetCat.isSelected()) {
            petsList.add("cat");
        }
        if (cbPetDog.isSelected()) {
            petsList.add("dog");
        }
        if (cbPetOther.isSelected()) {
            petsList.add("other");
        }
        String pets = String.join(",", petsList);
        //
        String continent = (String)comboContinent.getSelectedItem();
        int tempC = sliderTemp.getValue();
        //
        String line = String.format("%s;%s;%s;%s;%d", name, age, pets, continent, tempC);
        System.out.println(line);
        // true as the 2nd parameter of FileWriter's constructor makes it append
        try (PrintWriter outputFile = new PrintWriter(new FileWriter(new File("output.txt"), true))) {
            outputFile.println(line);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    "Writing to file failed\n" + ex.getMessage(),
                    "File access error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Day06ManyInputs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Day06ManyInputs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Day06ManyInputs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Day06ManyInputs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Day06ManyInputs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegister;
    private javax.swing.ButtonGroup buttonGroupAge;
    private javax.swing.JCheckBox cbPetCat;
    private javax.swing.JCheckBox cbPetDog;
    private javax.swing.JCheckBox cbPetOther;
    private javax.swing.JComboBox<String> comboContinent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JRadioButton rbAge18to35;
    private javax.swing.JRadioButton rbAge36andUp;
    private javax.swing.JRadioButton rbAgeBelow18;
    private javax.swing.JSlider sliderTemp;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
